# This is a basic workflow to help you get started with Actions

name: Test_available_docker-compose_work
# Controls when the workflow will run
on:
  push:
    branches: 
      - compose
    
jobs:
  docker:
    runs-on: ubuntu-latest
   
    steps:
    
    - name: Copy all files from repo
      uses: actions/checkout@v3
      with:
        ref: compose  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: kolia2526/nginx:latest    
    
    - name: docker-compose start 
      run : docker-compose up -d 
   
    - name: Congrats! 
      run : echo "Services push and work"
