# This is a basic workflow to help you get started with Actions

name: Docker-test-webpage
env:
 DOCKER_ID: docker ps -a|awk '{print $1}'|grep -v "CONTAINER"|grep -m1 ""
# Controls when the workflow will run
on:
  push:
    branches: 
      - main
    
jobs:
  docker:
    runs-on: ubuntu-latest
   
    steps:
    - name: Run dockerfile
      uses: actions/checkout@v1

    - name: Run webpage
      run : | 
        chmod +x docker.sh
        sudo ./docker.sh
    - name: dolby
      run : $(DOCKER_ID)
    - name: Test available files in docker continer
      run : docker exec -it $() ls -lah /usr/share/nginx/html
