# This is a basic workflow to help you get started with Actions

name: Docker-test-webpage
env:
 DOCKER_ID: docker ps -a | awk '{print $1}' | grep -m2  "" | grep -v "CONTAINER"
# Controls when the workflow will run
on:
  push:
    branches: 
      - main
    
jobs:
  docker:
    runs-on: ubuntu-latest
   
    steps:
    - name: Run dockerfile
      uses: actions/checkout@v1

    - name: Run webpage
      run : | 
        chmod +x docker.sh
        ./docker.sh
        
    - name: Test available files in docker continer
      run : docker exec -it ${{ DOCKER_ID }} ls -lah /usr/share/nginx/html
