# This is a basic workflow to help you get started with Actions

 name: Docker-test-webpage

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
jobs:

  docker run:
      runs-on: ubuntu-latest
  
      steps:
        - name: Run dockerfile
        - uses: actions/checkout@v1
        - run: |
            chmod +x docker.sh
            ./docker.sh
