# This is a basic workflow to help you get started with Actions

name: Docker-test-webpage

# Controls when the workflow will run
on:
  push:
    branches: 
      - main
    
jobs:
  docker:
    runs-on: ubuntu-latest
  
    steps:
    - name: Run dockerfile
      uses: actions/checkout@v1

    steps:
    - name: Run webpage
      run : | 
        chmod +x docker.sh
        ./docker.sh

    - name: ls -lah 
      run : ls -alh
